disabled_rules:
  - todo
  - nesting
  - line_length
  - file_name
  - trailing_whitespace
excluded:
  - Pods
  - R.generated.swift
  - IAA/Code/Utility/Database/Models
identifier_name:
  excluded:
    - at
    - id
    - on
    - x
    - y
    - vc
large_tuple:
  warning: 4
function_parameter_count: 6
analyzer_rules:
 - unused_declaration
 - unused_import
opt_in_rules:
  - anyobject_protocol
  - array_init
  - redundant_objc_attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
#  - extension_access_modifier:
#    excluded:
#    - "Day+CoreDataProperties.swift"
  - fallthrough
  - fatal_error_message
  - first_where
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition
